# Generated by Django 3.1.6 on 2023-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0002_auto_20230312_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusparameter',
            name='max_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statusposdetail',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
