# Generated by Django 3.1.6 on 2023-01-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0002_auto_20230123_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajetcoordonneer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculeno', models.CharField(max_length=100)),
                ('driver_oname', models.CharField(max_length=150)),
                ('driver_mobile_number', models.CharField(max_length=50)),
                ('FromPlace', models.CharField(max_length=150)),
                ('ToPlace', models.CharField(max_length=150)),
                ('id_trip', models.IntegerField()),
                ('trip_no', models.IntegerField()),
                ('trip_start_date', models.CharField(max_length=15)),
                ('pick_up_time', models.TimeField()),
                ('PickUp_H_Pos', models.CharField(max_length=100)),
            ],
        ),
    ]
