# Generated by Django 3.1.6 on 2023-03-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0003_auto_20230313_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refresh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='trajetcoordonnee',
            name='refresh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suiviVehicule.refresh'),
        ),
    ]
