# Generated by Django 3.1.6 on 2023-01-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0003_trajetcoordonneer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trajetcoordonneer',
            new_name='Trajetcoordonnee',
        ),
    ]
