# Generated by Django 3.1.6 on 2023-01-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0004_auto_20230124_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trajetcoordonnee',
            old_name='vehiculeno',
            new_name='vehicleno',
        ),
    ]
