# Generated by Django 3.1.6 on 2023-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0004_auto_20230314_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(max_length=50, null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('IMEI', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('GroupName', models.CharField(max_length=100, null=True)),
                ('CompanyName', models.CharField(max_length=100, null=True)),
                ('PhoneNumber', models.CharField(max_length=100, null=True)),
                ('UnitType', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
