# Generated by Django 3.1.6 on 2023-01-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0005_auto_20230124_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajetcoordonnee',
            name='trip_start_date',
            field=models.CharField(max_length=15),
        ),
    ]
