# Generated by Django 3.1.6 on 2023-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0005_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcomment',
            name='current',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
