# Generated by Django 3.1.6 on 2023-01-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0006_auto_20230124_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajetcoordonnee',
            name='trip_start_date',
        ),
    ]
