# Generated by Django 3.1.6 on 2023-03-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0007_auto_20230322_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planninglib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleno', models.CharField(max_length=100)),
                ('driver_oname', models.CharField(max_length=150)),
                ('driver_mobile_number', models.CharField(max_length=50)),
                ('FromPlace', models.CharField(max_length=150)),
                ('ToPlace', models.CharField(max_length=150)),
                ('id_trip', models.IntegerField()),
                ('trip_no', models.IntegerField()),
                ('trip_start_date', models.CharField(max_length=15)),
                ('pick_up_time', models.TimeField()),
                ('PickUp_H_Pos', models.CharField(max_length=100)),
                ('resa_trans_type', models.CharField(max_length=100)),
                ('daty_time', models.DateTimeField(null=True)),
                ('daterecord', models.DateField(null=True)),
                ('actualtime', models.TimeField(null=True)),
            ],
            options={
                'db_table': 'suivivehicule_planninglib',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleno', models.CharField(max_length=100)),
                ('driver_oname', models.CharField(max_length=150)),
                ('driver_mobile_number', models.CharField(max_length=50)),
                ('FromPlace', models.CharField(max_length=150)),
                ('ToPlace', models.CharField(max_length=150)),
                ('id_trip', models.IntegerField()),
                ('trip_no', models.IntegerField()),
                ('trip_start_date', models.CharField(max_length=15)),
                ('pick_up_time', models.TimeField()),
                ('PickUp_H_Pos', models.CharField(max_length=100)),
                ('resa_trans_type', models.CharField(max_length=100)),
                ('daty_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='difftimepickup',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='difftimestart',
            field=models.FloatField(null=True),
        ),
    ]
