# Generated by Django 3.1.6 on 2023-01-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0007_remove_trajetcoordonnee_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetcoordonnee',
            name='trip_start_date',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
