# Generated by Django 3.1.6 on 2023-01-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0008_trajetcoordonnee_trip_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuspos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statusposdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('coordonnee', models.CharField(max_length=100)),
                ('idmere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suiviVehicule.statuspos')),
            ],
        ),
    ]
