# Generated by Django 3.1.6 on 2023-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0008_auto_20230323_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='gpsid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
