# Generated by Django 3.1.6 on 2023-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0009_planning_gpsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordexport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trip', models.IntegerField()),
                ('comment', models.TextField(max_length=500)),
                ('vehicleno', models.CharField(max_length=100)),
                ('driver_oname', models.CharField(max_length=150)),
                ('FromPlace', models.CharField(max_length=150)),
                ('ToPlace', models.CharField(max_length=150)),
                ('trip_start_date', models.CharField(max_length=15)),
                ('pick_up_time', models.CharField()),
                ('status', models.CharField(max_length=100, null=True)),
                ('couleur', models.CharField(max_length=100, null=True)),
                ('daterecord', models.DateField()),
                ('etat', models.IntegerField(default=0)),
                ('driver_mobile_number', models.CharField(max_length=50)),
                ('current', models.CharField(max_length=150, null=True)),
                ('actualtime', models.CharField()),
                ('difftimestart', models.FloatField(null=True)),
                ('difftimepickup', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'suivivehicule_recordtrajet_export',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='statuspos',
            name='nbre',
            field=models.IntegerField(null=True),
        ),
    ]
