# Generated by Django 3.1.6 on 2023-01-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0010_trajetcoordonneesummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trajetcoordonneesummary',
            options={'managed': False},
        ),
    ]
