# Generated by Django 3.1.6 on 2023-03-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0010_auto_20230328_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recaprefresh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_refresh', models.IntegerField()),
                ('nbre_call_api', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'suivivehicule_recaprefresh',
                'managed': False,
            },
        ),
    ]
