# Generated by Django 3.1.6 on 2023-01-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0011_auto_20230125_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trajetcoordonneesummary',
            options={},
        ),
    ]
