# Generated by Django 3.1.6 on 2023-04-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0011_recaprefresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusposdetail',
            name='daty_api_google',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='statusposdetail',
            name='is_call_api',
            field=models.IntegerField(null=True),
        ),
    ]
