# Generated by Django 3.1.6 on 2024-07-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0012_auto_20230428_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_time', models.IntegerField()),
                ('type', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
        ),
    ]
