# Generated by Django 3.1.6 on 2024-09-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0012_auto_20230428_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonCancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_name', models.CharField(max_length=100)),
                ('reason_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_time', models.IntegerField()),
                ('type', models.CharField(max_length=150)),
                ('value', models.IntegerField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('desce', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='engineStatus',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='engineTime',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='ignition',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='odometer',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='speedMeasure',
            field=models.CharField(default='kph', max_length=150),
        ),
        migrations.AddField(
            model_name='statusposdetail',
            name='engineStatus',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='statusposdetail',
            name='engineTime',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='statusposdetail',
            name='ignition',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='statusposdetail',
            name='odometer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='statusposdetail',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusposdetail',
            name='speedMeasure',
            field=models.CharField(default='kph', max_length=150),
        ),
        migrations.CreateModel(
            name='SubReasonCancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_reason_name', models.CharField(max_length=100)),
                ('sub_reason_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_reasons', to='suiviVehicule.reasoncancel')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonCancelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='suiviVehicule.reasoncancel')),
                ('record_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_records', to='suiviVehicule.recordcomment')),
            ],
        ),
    ]
