# Generated by Django 3.1.6 on 2023-01-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0012_auto_20230125_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='UidName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleno', models.CharField(max_length=100)),
                ('Uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Trajetcoordonneesummary',
        ),
    ]
