# Generated by Django 3.1.6 on 2023-03-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0012_auto_20230320_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusposdetail',
            name='coordonnee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statusposdetail',
            name='current',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
