# Generated by Django 3.1.6 on 2023-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0013_auto_20230125_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetcoordonnee',
            name='PickEnd_H_Pos',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
