# Generated by Django 3.1.6 on 2024-09-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0013_auto_20240921_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubReasonCancelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_comment_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cancel_records', to='suiviVehicule.recordcomment')),
                ('sub_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_records', to='suiviVehicule.subreasoncancel')),
            ],
        ),
    ]
