# Generated by Django 3.1.6 on 2024-07-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0013_refreshtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtime',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
