# Generated by Django 3.1.6 on 2023-01-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0014_trajetcoordonnee_pickend_h_pos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uidname',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='uidname',
            table='UidName',
        ),
    ]
