# Generated by Django 3.1.6 on 2024-09-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0014_subreasoncancelrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoncancelrecord',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subreasoncancelrecord',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
