# Generated by Django 3.1.6 on 2024-07-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0014_refreshtime_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtime',
            name='desce',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
