# Generated by Django 3.1.6 on 2024-09-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0015_auto_20240921_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubReasonCancelRecordV1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.BooleanField()),
                ('record_comment_sub_id', models.IntegerField()),
                ('sub_reason_id', models.IntegerField()),
                ('sub_reason_name', models.CharField(max_length=255)),
                ('sub_reason_description', models.TextField()),
                ('reason_name', models.CharField(max_length=255)),
                ('reason_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'suivivehicule_subreasoncancelrecord_v1',
                'managed': False,
            },
        ),
    ]
