# Generated by Django 3.1.6 on 2024-09-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0016_subreasoncancelrecordv1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoncancel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
