# Generated by Django 3.1.6 on 2024-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0017_reasoncancel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreasoncancel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
