# Generated by Django 3.1.6 on 2024-09-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0018_subreasoncancel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusposdetail',
            name='modified',
            field=models.IntegerField(default=0),
        ),
    ]
