# Generated by Django 3.1.6 on 2023-01-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0018_trajetcoordonnee_pickend_h_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetcoordonnee',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
