# Generated by Django 3.1.6 on 2023-01-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0019_trajetcoordonnee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetcoordonnee',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
