# Generated by Django 3.1.6 on 2024-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0020_statusposmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trip', models.IntegerField(null=True)),
                ('uid', models.CharField(max_length=50, null=True)),
                ('daty_time', models.DateTimeField()),
                ('speed', models.IntegerField(default=0)),
                ('speedMeasure', models.CharField(default='kph', max_length=150)),
                ('odometer', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ignition', models.CharField(max_length=150, null=True)),
                ('engineTime', models.CharField(max_length=150, null=True)),
                ('engineStatus', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
