# Generated by Django 3.1.6 on 2023-01-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0020_trajetcoordonnee_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetcoordonnee',
            name='couleur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
