# Generated by Django 3.1.6 on 2024-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0021_bankposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankposition',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
