# Generated by Django 3.1.6 on 2023-01-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0021_trajetcoordonnee_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusposdetail',
            name='datetime',
            field=models.DateTimeField(default=True),
        ),
        migrations.AddField(
            model_name='statusposdetail',
            name='duration',
            field=models.IntegerField(default=True),
        ),
    ]
