# Generated by Django 3.1.6 on 2023-01-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0022_auto_20230126_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusposdetail',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='statusposdetail',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
