# Generated by Django 3.1.6 on 2024-09-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0023_auto_20240929_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankposition',
            name='engineTime',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bankposition',
            name='odometer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
