# Generated by Django 3.1.6 on 2024-09-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0024_auto_20240929_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcomment',
            name='engineTime',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='odometer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
