# Generated by Django 3.1.6 on 2024-09-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0025_auto_20240930_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPosMinBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trip', models.IntegerField(null=True)),
                ('uid', models.CharField(max_length=50, null=True)),
                ('daty_time', models.DateTimeField()),
                ('duration', models.IntegerField(null=True)),
                ('distance', models.FloatField(null=True)),
                ('speed', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('speedMeasure', models.CharField(default='kph', max_length=150)),
                ('odometer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ignition', models.CharField(max_length=150, null=True)),
                ('engineTime', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('engineStatus', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'suivivehicule_statuspos_min_transit',
                'managed': False,
            },
        ),
    ]
