# Generated by Django 3.1.6 on 2024-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0026_statusposminbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcomment',
            name='catno',
            field=models.IntegerField(default=0),
        ),
    ]
