# Generated by Django 3.1.6 on 2023-01-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0026_auto_20230126_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusposdetail',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
