# Generated by Django 3.1.6 on 2023-01-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0027_auto_20230126_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusposdetail',
            old_name='datetime',
            new_name='daty_time',
        ),
    ]
