# Generated by Django 5.1.2 on 2024-10-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suiviVehicule", "0027_recordcomment_catno"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrajetcoordonneeVehicleInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicleno", models.CharField(max_length=100)),
                ("driver_oname", models.CharField(max_length=150)),
                ("driver_mobile_number", models.CharField(max_length=50)),
                ("FromPlace", models.CharField(max_length=150)),
                ("ToPlace", models.CharField(max_length=150)),
                ("id_trip", models.IntegerField()),
                ("trip_no", models.IntegerField()),
                ("trip_start_date", models.CharField(max_length=15)),
                ("pick_up_time", models.TimeField()),
                ("PickUp_H_Pos", models.CharField(max_length=100)),
                ("PickEnd_H_Pos", models.CharField(max_length=100, null=True)),
                ("status", models.CharField(max_length=100, null=True)),
                ("duration", models.CharField(max_length=100, null=True)),
                ("couleur", models.CharField(max_length=100, null=True)),
                ("estimatetime", models.CharField(max_length=50, null=True)),
                ("datetime", models.CharField(max_length=15)),
                ("Uid", models.CharField(max_length=50, null=True)),
                ("idstatusposdetail", models.IntegerField(null=True)),
                ("trip_start_time", models.TimeField()),
                ("idstatusparameter", models.IntegerField(null=True)),
                ("difftimestart", models.FloatField()),
                ("difftimepickup", models.FloatField()),
                ("lateby", models.FloatField()),
                ("current", models.CharField(max_length=150, null=True)),
                (
                    "speed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("speedMeasure", models.CharField(default="kph", max_length=150)),
                (
                    "odometer",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("ignition", models.CharField(max_length=150, null=True)),
                (
                    "engineTime",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
                ),
                ("engineStatus", models.CharField(max_length=150, null=True)),
            ],
            options={
                "db_table": "suivivehicule_laststatuswithvehiculeinfo",
                "managed": False,
            },
        ),
    ]
