# Generated by Django 3.1.6 on 2023-01-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviVehicule', '0028_auto_20230126_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetcoordonnee',
            name='estimatetime',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
