# Generated by Django 5.1.2 on 2024-10-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suiviVehicule", "0029_tripmessagesending"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripMessageSendingLib",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_send", models.BooleanField(default=False)),
                ("vehicleno", models.CharField(max_length=100)),
                ("driver_oname", models.CharField(max_length=150)),
                ("driver_mobile_number", models.CharField(max_length=50)),
                ("FromPlace", models.CharField(max_length=150)),
                ("ToPlace", models.CharField(max_length=150)),
                ("id_trip", models.IntegerField()),
                ("pick_up_time", models.TimeField()),
                ("PickUp_H_Pos", models.CharField(max_length=100)),
                ("resa_trans_type", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "suivivehicule_tripmessagesendinglib",
                "managed": False,
            },
        ),
        migrations.RemoveField(model_name="tripmessagesending", name="planning",),
        migrations.AddField(
            model_name="tripmessagesending",
            name="id_trip",
            field=models.IntegerField(null=True),
        ),
    ]
