# Generated by Django 5.1.2 on 2024-10-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suiviVehicule", "0030_tripmessagesendinglib_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusposdetail",
            name="annulated",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="statusposdetail",
            name="completed",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="statusposdetail",
            name="risky",
            field=models.FloatField(default=0),
        ),
    ]
