# Generated by Django 5.1.2 on 2024-11-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "suiviVehicule",
            "0031_statusposdetail_annulated_statusposdetail_completed_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TrajetDetailInfoVehicule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_trip", models.IntegerField()),
                ("duration", models.CharField(max_length=100, null=True)),
                ("daty_time", models.CharField(max_length=15)),
                ("Uid", models.CharField(max_length=50, null=True)),
                ("current", models.CharField(max_length=150, null=True)),
                (
                    "speed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("speedMeasure", models.CharField(default="kph", max_length=150)),
                (
                    "odometer",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("ignition", models.CharField(max_length=150, null=True)),
                (
                    "engineTime",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
                ),
                ("engineStatus", models.CharField(max_length=150, null=True)),
                ("annulated", models.FloatField(default=0)),
                ("risky", models.FloatField(default=0)),
                ("completed", models.FloatField(default=0)),
            ],
            options={"db_table": "suivivehicule_detailinfovehicule", "managed": False,},
        ),
        migrations.CreateModel(
            name="TypeRapport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelTable(
            name="recaprefresh", table="suivivehicule_recaprefresh_withprice",
        ),
        migrations.CreateModel(
            name="RapportAuto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "sent_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_to",
                        to="auth.group",
                    ),
                ),
                (
                    "type_rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_rapport",
                        to="suiviVehicule.typerapport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogRapportAuto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(max_length=100, null=True)),
                ("result", models.TextField()),
                ("status", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rapport_auto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapport_auto",
                        to="suiviVehicule.rapportauto",
                    ),
                ),
            ],
        ),
    ]
