# Generated by Django 5.1.2 on 2024-11-20 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suiviVehicule", "0032_trajetdetailinfovehicule_typerapport_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
        migrations.AddField(
            model_name="lograpportauto",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
